#!/usr/bin/env bash
printf "%s\n" "$(tput bold)$(date) ${BASH_SOURCE[0]}$(tput sgr0)"

# Create build directory
mkdir -p /opt/gcc-build
cd /opt/gcc-build

# Download GCC 15.1.0 (adjust URL when available, using 14.1.0 as example)
# Note: GCC 15.1.0 might not be released yet, using 14.1.0 as example
wget https://gcc.gnu.org/releases/gcc-14.1.0/gcc-14.1.0.tar.xz
tar -xf gcc-14.1.0.tar.xz
cd gcc-14.1.0

# Download prerequisites
./contrib/download_prerequisites

# Create build directory outside source
cd ..
mkdir gcc-build
cd gcc-build

# Configure GCC build
../gcc-14.1.0/configure \
  --prefix=/usr/local/gcc-15 \
  --enable-languages=c,c++,fortran \
  --enable-multilib \
  --enable-threads=posix \
  --enable-checking=release \
  --with-system-zlib \
  --disable-bootstrap

# Build GCC (this will take several hours)
make -j$(nproc)

# Install
make install

# Add to PATH
echo 'export PATH=/usr/local/gcc-15/bin:$PATH' >> ~/.bashrc
echo 'export LD_LIBRARY_PATH=/usr/local/gcc-15/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc
source ~/.bashrc
